export const catalogPhotoSlugs = [
  "tomato",
  "big-onion",
  "shallots",
  "potato",
  "green-chilli",
  "brinjal",
  "bitter-gourd",
  "snake-gourd",
  "long-beans",
  "ginger",
  "garlic",
  "carrot",
  "beetroot",
  "cabbage",
  "cauliflower",
  "ash-gourd",
  "pumpkin",
  "cucumber",
  "ladies-finger",
  "raw-banana",
  "elephant-foot-yam",
  "colocasia",
  "tapioca",
  "capsicum",
  "french-beans",
  "ivy-gourd",
  "ridge-gourd",
  "bottle-gourd",
  "cluster-beans",
  "drumstick",
  "radish",
  "sweet-potato",
  "raw-papaya",
  "mushroom",
  "green-peas",
  "lemon-cucumber",
  "banana-robusta",
  "banana-nendran",
  "papaya",
  "mango",
  "watermelon",
  "pineapple",
  "guava",
  "sapota",
  "grapes-black",
  "apple",
  "orange",
  "avocado",
  "pomegranate",
  "red-amaranthus",
  "spinach",
  "moringa-leaves",
  "curry-leaves",
  "coriander-leaves",
  "mint-leaves",
  "spring-onion",
  "matta-rice",
  "sona-masoori-rice",
  "wheat-atta",
  "puttu-podi",
  "idiyappam-podi",
  "toor-dal",
  "chana-dal",
  "moong-dal",
  "urad-dal",
  "rava",
  "chilli-powder",
  "turmeric-powder",
  "coriander-powder",
  "pepper-black",
  "cardamom",
  "clove",
  "cumin-seeds",
  "mustard-seeds",
  "cinnamon",
  "garam-masala",
  "farm-eggs",
  "milk-pouch",
  "curd",
  "butter",
  "paneer",
  "coconut",
  "coconut-oil",
  "banana-chips",
  "jackfruit-chips",
  "achappam",
  "kozhikode-halwa",
  "bread",
  "tea-dust",
  "coffee-powder",
  "sugar",
  "salt",
  "jaggery",
  "jeerakasala-rice",
  "ghee",
  "sunflower-oil",
  "sarkara-varatti",
] as const;

export const categoryPhotoSlugs: Record<string, string> = {
  vegetables: "tomato",
  fruits: "mango",
  groceries: "sugar",
  "leafy-greens": "spinach",
  "rice-and-grains": "matta-rice",
  spices: "cardamom",
  "dairy-and-eggs": "milk-pouch",
  "coconut-and-oils": "coconut",
  "snacks-and-bakery": "achappam",
};
